from __future__ import annotations

import datetime
import math
from pathlib import Path

from alpha_lab.experiment import ExperimentResult

from .spec import SingleFactorCaseSpec


def render_summary_markdown(
    *,
    spec: SingleFactorCaseSpec,
    metrics: dict[str, object],
    output_dir: Path,
) -> str:
    """Render a concise human-readable run summary."""

    lines = [
        f"# Real-Case Single Factor Summary: {spec.name}",
        "",
        "## Run Context",
        "",
        f"- Case name: `{spec.name}`",
        f"- Factor: `{spec.factor_name}`",
        f"- Direction: `{spec.direction}`",
        f"- Universe: `{spec.universe.name}`",
        f"- Rebalance frequency: `{spec.rebalance_frequency}`",
        f"- Target: `{spec.target.kind}` (horizon={spec.target.horizon})",
        f"- Output directory: `{output_dir}`",
        "",
        "## Metrics",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Mean IC | {_fmt(metrics.get('mean_ic'))} |",
        f"| Mean Rank IC | {_fmt(metrics.get('mean_rank_ic'))} |",
        f"| ICIR | {_fmt(metrics.get('ic_ir'))} |",
        f"| Mean Long-Short Return | {_fmt(metrics.get('mean_long_short_return'))} |",
        f"| Mean Long-Short Turnover | {_fmt(metrics.get('mean_long_short_turnover'))} |",
        f"| Coverage Mean | {_fmt(metrics.get('coverage_mean'))} |",
        f"| Missingness Mean | {_fmt(metrics.get('missingness_mean'))} |",
        (
            "| Cost-Adjusted Mean L/S Return | "
            f"{_fmt(metrics.get('mean_cost_adjusted_long_short_return'))} |"
        ),
        "",
        "## Notes",
        "",
        (
            "- This file is auto-generated. Use `experiment_card.md` for "
            "research interpretation notes."
        ),
        "",
    ]
    return "\n".join(lines)


def render_experiment_card_markdown(
    *,
    spec: SingleFactorCaseSpec,
    metrics: dict[str, object],
    result: ExperimentResult,
) -> str:
    """Render vault-friendly experiment card markdown."""

    today = datetime.date.today().isoformat()
    tags = "[experiment, single_factor, quant]"
    lines = [
        "---",
        "type: experiment",
        f"name: {spec.name}",
        'source: "alpha-lab / real-case single-factor package"',
        f"tags: {tags}",
        "status: draft",
        f"factor: {spec.factor_name}",
        f"direction: {spec.direction}",
        f"horizon: {spec.target.horizon}",
        f"quantiles: {spec.n_quantiles}",
        f"rebalance_frequency: {spec.rebalance_frequency}",
        f"run_date: {today}",
        "---",
        "",
        f"# {spec.name}",
        "",
        "> *Auto-generated by `alpha-lab` real-case single-factor package.*  ",
        (
            "> *Setup and Results are auto-generated. Interpretation, Next Steps, "
            "Open Questions, and Notes are manual sections.*"
        ),
        "",
        "## Setup",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Factor | `{spec.factor_name}` |",
        f"| Direction | `{spec.direction}` |",
        f"| Universe | `{spec.universe.name}` |",
        f"| Target | `{spec.target.kind}` |",
        f"| Horizon | {spec.target.horizon} |",
        f"| Rebalance frequency | `{spec.rebalance_frequency}` |",
        f"| Transaction cost (one-way) | {_fmt(spec.transaction_cost.one_way_rate)} |",
        f"| Eval dates (finite IC) | {_fmt(metrics.get('n_dates_used'))} |",
        "",
        "## Results",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Mean IC | {_fmt(metrics.get('mean_ic'))} |",
        f"| Mean Rank IC | {_fmt(metrics.get('mean_rank_ic'))} |",
        f"| ICIR | {_fmt(metrics.get('ic_ir'))} |",
        f"| Mean Long-Short Return | {_fmt(metrics.get('mean_long_short_return'))} |",
        f"| Long-Short Hit Rate | {_fmt(metrics.get('long_short_hit_rate'))} |",
        f"| Mean Long-Short Turnover | {_fmt(metrics.get('mean_long_short_turnover'))} |",
        (
            "| Mean Cost-Adjusted L/S Return | "
            f"{_fmt(metrics.get('mean_cost_adjusted_long_short_return'))} |"
        ),
        f"| Coverage Mean | {_fmt(metrics.get('coverage_mean'))} |",
        "",
        "## Interpretation",
        "",
        "<!-- Manual: interpret statistical and economic significance -->",
        "",
        "## Next Steps",
        "",
        "<!-- Manual: define the next concrete research actions -->",
        "",
        "## Open Questions",
        "",
        "<!-- Manual: unresolved assumptions / data questions -->",
        "",
        "## Notes",
        "",
        f"- Provenance run timestamp UTC: `{result.provenance.run_timestamp_utc}`",
        f"- Git commit: `{result.provenance.git_commit or 'unknown'}`",
        "",
    ]
    return "\n".join(lines)


def _fmt(value: object) -> str:
    if value is None:
        return "—"
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return "—"
        return f"{value:.6f}"
    return str(value)
