from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

import pandas as pd

from alpha_lab.handoff import (
    EXECUTION_ASSUMPTIONS_SCHEMA_VERSION,
    HANDOFF_SCHEMA_VERSION,
    PORTFOLIO_CONSTRUCTION_SCHEMA_VERSION,
    ExecutionAssumptionsSpec,
    PortfolioConstructionSpec,
)

BACKTEST_ADAPTER_VERSION = "1.0.0"
SupportedEngine = Literal["vectorbt", "backtrader"]


@dataclass(frozen=True)
class AdapterWarning:
    """One explicit warning generated by the adapter layer."""

    code: str
    message: str


@dataclass
class BacktestInputBundle:
    """Standardized in-memory representation of a handoff bundle."""

    artifact_path: Path
    schema_version: str
    manifest: dict[str, object]
    signal_snapshot_df: pd.DataFrame
    universe_mask_df: pd.DataFrame
    tradability_mask_df: pd.DataFrame
    timing_payload: dict[str, object]
    experiment_metadata_payload: dict[str, object]
    validation_context_payload: dict[str, object]
    dataset_fingerprint_payload: dict[str, object]
    portfolio_construction: PortfolioConstructionSpec
    execution_assumptions: ExecutionAssumptionsSpec
    exclusion_reasons_df: pd.DataFrame | None = None
    label_snapshot_df: pd.DataFrame | None = None

    @property
    def experiment_id(self) -> str | None:
        raw = self.experiment_metadata_payload.get("experiment_id")
        return None if raw is None else str(raw)

    @property
    def dataset_fingerprint(self) -> str | None:
        raw = self.dataset_fingerprint_payload.get("fingerprint")
        return None if raw is None else str(raw)

    @property
    def signal_name(self) -> str:
        names = pd.unique(self.signal_snapshot_df["signal_name"].astype(str))
        if len(names) != 1:
            raise ValueError(
                "signal_snapshot must contain exactly one signal_name for adapter use"
            )
        signal_name = str(names[0]).strip()
        if not signal_name:
            raise ValueError("signal_name must be non-empty")
        return signal_name


@dataclass(frozen=True)
class PortfolioIntentFrame:
    """Deterministic per-date target weights derived from one bundle."""

    intent_method: str
    target_weights_df: pd.DataFrame
    diagnostics_df: pd.DataFrame
    warnings: tuple[AdapterWarning, ...] = field(default_factory=tuple)


@dataclass(frozen=True)
class BacktestRunConfig:
    """Runtime config for one external adapter replay."""

    price_df: pd.DataFrame
    engine: SupportedEngine = "vectorbt"
    close_column: str = "close"
    open_column: str | None = None
    initial_cash: float = 1_000_000.0
    freq: str | None = None
    commission_bps: float = 0.0
    slippage_bps: float = 0.0
    output_dir: Path | None = None
    export_summary: bool = True
    export_target_weights: bool = False
    export_series: bool = True

    def __post_init__(self) -> None:
        if self.initial_cash <= 0.0:
            raise ValueError("initial_cash must be > 0")
        if self.commission_bps < 0.0:
            raise ValueError("commission_bps must be >= 0")
        if self.slippage_bps < 0.0:
            raise ValueError("slippage_bps must be >= 0")
        if not self.close_column.strip():
            raise ValueError("close_column must be non-empty")
        if self.open_column is not None and not self.open_column.strip():
            raise ValueError("open_column must be non-empty when provided")


@dataclass
class BacktestResult:
    """Standardized replay result returned by one engine adapter."""

    engine: SupportedEngine
    artifact_path: Path
    experiment_id: str | None
    dataset_fingerprint: str | None
    target_weights_df: pd.DataFrame
    executed_weights_df: pd.DataFrame
    returns_df: pd.DataFrame
    equity_curve_df: pd.DataFrame
    turnover_df: pd.DataFrame
    summary: dict[str, object]
    warnings: tuple[AdapterWarning, ...] = field(default_factory=tuple)
    engine_stats: dict[str, object] | None = None
    adapter_run_metadata: dict[str, object] | None = None
    orders_df: pd.DataFrame | None = None
    trades_df: pd.DataFrame | None = None
    skipped_orders_df: pd.DataFrame | None = None
    output_files: dict[str, Path] = field(default_factory=dict)


def validate_adapter_schema_versions(
    portfolio_construction: PortfolioConstructionSpec,
    execution_assumptions: ExecutionAssumptionsSpec,
    *,
    bundle_schema_version: str,
) -> None:
    """Guard against schema-version drift between bundle and adapter parser."""

    if bundle_schema_version != HANDOFF_SCHEMA_VERSION:
        raise ValueError(
            f"adapter currently supports handoff schema {HANDOFF_SCHEMA_VERSION!r}; "
            f"got {bundle_schema_version!r}"
        )
    if portfolio_construction.schema_version != PORTFOLIO_CONSTRUCTION_SCHEMA_VERSION:
        raise ValueError(
            "unsupported portfolio construction schema_version "
            f"{portfolio_construction.schema_version!r}; expected "
            f"{PORTFOLIO_CONSTRUCTION_SCHEMA_VERSION!r}"
        )
    if execution_assumptions.schema_version != EXECUTION_ASSUMPTIONS_SCHEMA_VERSION:
        raise ValueError(
            "unsupported execution assumptions schema_version "
            f"{execution_assumptions.schema_version!r}; expected "
            f"{EXECUTION_ASSUMPTIONS_SCHEMA_VERSION!r}"
        )
